version: "3.9"

services:
  node-0:
    image: aequa-local:latest
    container_name: aequa-testnet-tss-0
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620","--enable-tss"]
    ports:
      - "4600:4600"
      - "4620:4620"

  node-1:
    image: aequa-local:latest
    container_name: aequa-testnet-tss-1
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620","--enable-tss"]
    ports:
      - "4601:4600"
      - "4621:4620"

  node-2:
    image: aequa-local:latest
    container_name: aequa-testnet-tss-2
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620","--enable-tss"]
    ports:
      - "4602:4600"
      - "4622:4620"

  node-3:
    image: aequa-local:latest
    container_name: aequa-testnet-tss-3
    command: ["--validator-api","0.0.0.0:4600","--monitoring","0.0.0.0:4620","--enable-tss"]
    ports:
      - "4603:4600"
      - "4623:4620"